// Generated by CoffeeScript 1.3.3
(function() {
  var desired, geocode, query;

  $(function() {
    return geocode('10552');
  });

  desired = [114, 151, 156, 153, 145, 144, 114, 151, 163, 164, 116, 131, 103];

  geocode = function(address) {
    return $.ajax({
      url: "./geocode_request.php?address=" + address,
      type: 'GET',
      success: function(data) {
        var coords, lat, lng, location;
        location = JSON.parse(data).results[0].geometry.location;
        lat = location.lat;
        lng = location.lng;
        coords = "" + lat + "," + lng;
        return query(coords);
      }
    });
  };

  query = function(coords) {
    return $.ajax({
      url: "./request.php?location=" + coords + "&radius=5000&types=food&name=starbucks",
      type: 'GET',
      success: function(data) {
        var results;
        results = JSON.parse(data).results;
        results = _.map(results, function(result) {
          var _ref;
          return (_ref = result.vicinity.match(/^\d+/)) != null ? _ref[0] : void 0;
        });
        return console.log(results);
      }
    });
  };

}).call(this);
