// Generated by CoffeeScript 1.3.3
(function() {
  var callback, initialize, query;

  $(function() {
    return initialize();
  });

  query = function() {
    var key;
    return key = 'AIzaSyAa5R9714gGFc7NOFFuIeFmFTM11Z-CW2s';
  };

  initialize = function() {
    var infowindow, map, pyrmont, request, service;
    pyrmont = new google.maps.LatLng(-33.8665433, 151.1956316);
    map = new google.maps.Map($('#map'), {
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      center: pyrmont,
      zoom: 15
    });
    request = {
      location: pyrmont,
      radius: 500,
      types: ['store']
    };
    infowindow = new google.maps.InfoWindow();
    service = new google.maps.places.PlacesService(map);
    return service.nearbySearch(request, callback);
  };

  callback = function(results, status) {
    return console.log(results, status);
  };

}).call(this);
